/*
 * generated by Xtext
 */
package person.zhoujg.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import person.zhoujg.services.FeatureGrammarAccess;

@SuppressWarnings("all")
public class FeatureSyntacticSequencer extends AbstractSyntacticSequencer {

	protected FeatureGrammarAccess grammarAccess;
	protected AbstractElementAlias match_LogicExpr___ExclamationMarkKeyword_0_0_or_NotKeyword_0_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (FeatureGrammarAccess) access;
		match_LogicExpr___ExclamationMarkKeyword_0_0_or_NotKeyword_0_1__q = new AlternativeAlias(false, true, new TokenAlias(false, false, grammarAccess.getLogicExprAccess().getExclamationMarkKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getLogicExprAccess().getNotKeyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_LogicExpr___ExclamationMarkKeyword_0_0_or_NotKeyword_0_1__q.equals(syntax))
				emit_LogicExpr___ExclamationMarkKeyword_0_0_or_NotKeyword_0_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('!' | 'not')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) leftLogicExpr=BasicExpr
	 */
	protected void emit_LogicExpr___ExclamationMarkKeyword_0_0_or_NotKeyword_0_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
