/*
 * generated by Xtext
 */
package person.zhoujg.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractFeatureValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(person.zhoujg.feature.FeaturePackage.eINSTANCE);
		return result;
	}
}
