/*
 * generated by Xtext
 */
package person.zhoujg.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import person.zhoujg.ui.internal.FeatureActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FeatureExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FeatureActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FeatureActivator.getInstance().getInjector(FeatureActivator.PERSON_ZHOUJG_FEATURE);
	}
	
}
