/*
* generated by Xtext
*/
package person.zhoujg;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FeatureStandaloneSetup extends FeatureStandaloneSetupGenerated{

	public static void doSetup() {
		new FeatureStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

