/**
 * generated by Xtext
 */
package person.zhoujg.ui.contentassist;

import person.zhoujg.ui.contentassist.AbstractFeatureProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class FeatureProposalProvider extends AbstractFeatureProposalProvider {
}
