/*
 * generated by Xtext
 */
package person.zhoujg;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FeatureUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return person.zhoujg.ui.internal.FeatureActivator.getInstance().getInjector("person.zhoujg.Feature");
	}
	
}
